package main.models;

public class Task {
    private String ID;
    private String assignedProjectID;
    private String name;
    private Status status;
    private Priority priority;

    public Task(String ID, String assignedProjectID, String name, Status status, Priority priority) {
        this.ID = ID;
        this.assignedProjectID = assignedProjectID;
        this.name = name;
        this.status = status;
        this.priority = priority;
    }

//    getters

    public String getID() {
        return ID;
    }

    public String getAssignedProjectID() {
        return assignedProjectID;
    }

    public Priority getPriority() {
        return priority;
    }

    public Status getStatus() {
        return status;
    }

    public String getName() {
        return name;
    }


//    setters

    public void setAssignedProjectID(String assignedProjectID) {
        this.assignedProjectID = assignedProjectID;
    }
// removed. to be autogenerated
//    public void setID(String ID) {
//        this.ID = ID;
//    }

    public void setName(String name) {
        this.name = name;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    //    display methods
public void displayTask(){
    System.out.println("Task ID: "+ ID);
    System.out.println("Assigned Project: Project ID " + assignedProjectID);
    System.out.println("Task Name: " + name);
    System.out.println("Task Status: "+ status);
    System.out.println("Priority: " + priority);
}

    @Override
    public String toString() {
        return String.format(
                "Task ID: %s\nAssigned Project: Project ID %s\nTask Name: %s\nTask Status: %s\nPriority: %s ",
                ID, assignedProjectID, name, status, priority
        );
    }




}
